global:
  name: pretrain-vision-model
  phase: train
  stage: pretrain-vision
  workdir: workdir
  seed: ~
 
dataset:
  train: {
    roots: ['/nlsasfs/home/ai4bharat/shubhamr/recognition-dataset/hindi/training/MJ/MJ_train/',
            '/nlsasfs/home/ai4bharat/shubhamr/recognition-dataset/hindi/training/MJ/MJ_test/',
            '/nlsasfs/home/ai4bharat/shubhamr/recognition-dataset/hindi/validation/MJ_valid',
            '/nlsasfs/home/ai4bharat/shubhamr/recognition-dataset/hindi/training/ST'],
    batch_size: 384
  }
  test: {
    roots: ['/nlsasfs/home/ai4bharat/shubhamr/recognition-dataset/hindi/evaluation/IIIT',
            '/nlsasfs/home/ai4bharat/shubhamr/recognition-dataset/hindi/evaluation/kaggle_train',
            '/nlsasfs/home/ai4bharat/shubhamr/recognition-dataset/hindi/evaluation/kaggle_val'
            ],
    batch_size: 384
  }
  data_aug: True
  multiscales: False
  num_workers: 12

training:
  epochs: 8
  show_iters: 50
  eval_iters: 3000
  save_iters: 3000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 2],
    gamma: 0.1,
  }

model:
  name: 'modules.model_vision.BaseVision'
  checkpoint: ~
  vision: {
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
