global:
  name: train-abinet
  phase: train
  stage: train-super
  workdir: workdir
  seed: ~
 
dataset:
  train: {
    roots: [ '/usr/datasets/synthetic_text_dataset/lmdb_dataset_Hindi/hindi/training/MJ/MJ_train/',
             '/usr/datasets/synthetic_text_dataset/lmdb_dataset_Hindi/hindi/training/MJ/MJ_test/',
             '/usr/datasets/synthetic_text_dataset/lmdb_dataset_Hindi/hindi/validation/MJ_valid',
             '/usr/datasets/synthetic_text_dataset/lmdb_dataset_Hindi/hindi/training/ST' ],
    batch_size: 384
  }
  test: {
    roots: [ '/usr/datasets/synthetic_text_dataset/lmdb_dataset_Hindi/hindi/evaluation/IIIT',
             '/usr/datasets/synthetic_text_dataset/lmdb_dataset_Hindi/hindi/evaluation/kaggle_train',
             '/usr/datasets/synthetic_text_dataset/lmdb_dataset_Hindi/hindi/evaluation/kaggle_val'
    ],
    batch_size: 384
  }
  data_aug: True
  multiscales: False
  num_workers: 14

training:
  epochs: 10
  show_iters: 50
  eval_iters: 5000
  save_iters: 5000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 4],
    gamma: 0.1,
  }

model:
  name: 'modules.model_abinet_iter.ABINetIterModel'
  iter_size: 3
  ensemble: ''
  use_vision: False
  vision: {
    checkpoint: /home/shubham/Documents/MTP/text-recognition-models/ABINet/workdir/pretrain-vision-model/pretrain-vision-model_0_1000.pth,
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
  language: {
    checkpoint:  /home/shubham/Documents/MTP/text-recognition-models/ABINet/workdir/pretrain-language-model/pretrain-language-model_0_1000.pth,
    num_layers: 4,
    loss_weight: 1.,
    detach: True,
    use_self_attn: False
  }
  alignment: {
    loss_weight: 1.,
  }
